// no # pragma once!
#ifdef BIGINT_TRACY_DEFINES_H

#undef BIGINT_TRACY_DEFINES_H
#undef BIGINT_TRACY_CONSTEXPR_AUTO
#undef BIGINT_TRACY_CONSTEXPR_AUTO_DISCARD
#undef BIGINT_TRACY_CONSTEXPR_VOID
#undef BIGINT_TRACY_CONSTEXPR
#undef BIGINT_TRACY_ZONE_SCOPED

#endif
